### ISSUE TITLE
Unable to build `grid_encoder` and `raymarching`

### ISSUE THREAD

**Issue by abhayraw1** [ashawkey/torch-ngp#104]
Hi,

I have been trying to set this project up and am struggling to get it running due to failure to build the `_raymarching`  and `_grid_encoder` module.

As mentioned in the readme, I tried to run the following:
`python main_sdf.py data/armadillo.obj --workspace trial_sdf`
which results in the following error!
```
-> % python main_sdf.py data/armadillo.obj --workspace trial_sdf
Namespace(ff=False, fp16=False, lr=0.0001, path='data/armadillo.obj', seed=0, tcnn=False, test=False, workspace='trial_sdf')
Traceback (most recent call last):
  File "/pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/gridencoder/grid.py", line 10, in <module>
    import _gridencoder as _backend
ModuleNotFoundError: No module named '_gridencoder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_sdf.py", line 32, in <module>
    model = SDFNetwork(encoding="hashgrid")
  File "/pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/sdf/netowrk.py", line 24, in __init__
    self.encoder, self.in_dim = get_encoder(encoding)
  File "/pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/encoding.py", line 64, in get_encoder
    from gridencoder import GridEncoder
  File "/pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/gridencoder/__init__.py", line 1, in <module>
    from .grid import GridEncoder
  File "/pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/gridencoder/grid.py", line 12, in <module>
    from .backend import _backend
  File "/pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/gridencoder/backend.py", line 34, in <module>
    sources=[os.path.join(_src_path, 'src', f) for f in [
  File "/mnt/sqnap_colomirror/abrawat/envs/torch3d/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1091, in load
    keep_intermediates=keep_intermediates)
  File "/mnt/sqnap_colomirror/abrawat/envs/torch3d/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1317, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/mnt/sqnap_colomirror/abrawat/envs/torch3d/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1699, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/mnt/sqnap_colomirror/abrawat/envs/torch3d/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_grid_encoder'
```

Following this I tried to manually install the `grid_encoder` package which gives the following traceback:
```
-> % cd gridencoder 
(torch3d) abrawat@sgscccdl0002 [06:13:40] [/pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/gridencoder] [main *]
-> % pip install .
Processing /pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/gridencoder
Building wheels for collected packages: gridencoder
  Building wheel for gridencoder (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /mnt/sqnap_colomirror/abrawat/envs/torch3d/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-_33twrrb/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-_33twrrb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-b0l6mk1j
       cwd: /tmp/pip-req-build-_33twrrb/
  Complete output (18 lines):
  running bdist_wheel
  running build
  running build_ext
  building '_gridencoder' extension
  creating /tmp/pip-req-build-_33twrrb/build
  creating /tmp/pip-req-build-_33twrrb/build/temp.linux-x86_64-cpython-37
  creating /tmp/pip-req-build-_33twrrb/build/temp.linux-x86_64-cpython-37/tmp
  creating /tmp/pip-req-build-_33twrrb/build/temp.linux-x86_64-cpython-37/tmp/pip-req-build-_33twrrb
  creating /tmp/pip-req-build-_33twrrb/build/temp.linux-x86_64-cpython-37/tmp/pip-req-build-_33twrrb/src
  Emitting ninja build file /tmp/pip-req-build-_33twrrb/build/temp.linux-x86_64-cpython-37/build.ninja...
  Compiling objects...
  Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
  1.10.2
  creating build/lib.linux-x86_64-cpython-37
  g++ -pthread -B /mnt/algo_train/anurbha/conda_envs/pytorch_1_8/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /mnt/algo_train/anurbha/conda_envs/pytorch_1_8/compiler_compat -L/mnt/algo_train/anurbha/conda_envs/pytorch_1_8/lib -Wl,-rpath=/mnt/algo_train/anurbha/conda_envs/pytorch_1_8/lib -Wl,--no-as-needed -Wl,--sysroot=/ /tmp/pip-req-build-_33twrrb/build/temp.linux-x86_64-cpython-37/tmp/pip-req-build-_33twrrb/src/bindings.o /tmp/pip-req-build-_33twrrb/build/temp.linux-x86_64-cpython-37/tmp/pip-req-build-_33twrrb/src/gridencoder.o -L/mnt/sqnap_colomirror/abrawat/envs/torch3d/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-cpython-37/_gridencoder.cpython-37m-x86_64-linux-gnu.so
  g++: error: /tmp/pip-req-build-_33twrrb/build/temp.linux-x86_64-cpython-37/tmp/pip-req-build-_33twrrb/src/bindings.o: No such file or directory
  g++: error: /tmp/pip-req-build-_33twrrb/build/temp.linux-x86_64-cpython-37/tmp/pip-req-build-_33twrrb/src/gridencoder.o: No such file or directory
  error: command '/usr/bin/g++' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for gridencoder
  Running setup.py clean for gridencoder
Failed to build gridencoder
WARNING: Error parsing requirements for yacs: [Errno 2] No such file or directory: '/mnt/sqnap_colomirror/abrawat/envs/torch3d/lib/python3.7/site-packages/yacs-0.1.8.dist-info/METADATA'
Installing collected packages: gridencoder
    Running setup.py install for gridencoder ... error
    ERROR: Command errored out with exit status 1:
     command: /mnt/sqnap_colomirror/abrawat/envs/torch3d/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-_33twrrb/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-_33twrrb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6y9cc4v7/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/sqnap_colomirror/abrawat/envs/torch3d/include/python3.7m/gridencoder
         cwd: /tmp/pip-req-build-_33twrrb/
    Complete output (20 lines):
    running install
    /mnt/sqnap_colomirror/abrawat/envs/torch3d/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    running build
    running build_ext
    building '_gridencoder' extension
    creating /tmp/pip-req-build-_33twrrb/build
    creating /tmp/pip-req-build-_33twrrb/build/temp.linux-x86_64-cpython-37
    creating /tmp/pip-req-build-_33twrrb/build/temp.linux-x86_64-cpython-37/tmp
    creating /tmp/pip-req-build-_33twrrb/build/temp.linux-x86_64-cpython-37/tmp/pip-req-build-_33twrrb
    creating /tmp/pip-req-build-_33twrrb/build/temp.linux-x86_64-cpython-37/tmp/pip-req-build-_33twrrb/src
    Emitting ninja build file /tmp/pip-req-build-_33twrrb/build/temp.linux-x86_64-cpython-37/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    1.10.2
    creating build/lib.linux-x86_64-cpython-37
    g++ -pthread -B /mnt/algo_train/anurbha/conda_envs/pytorch_1_8/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /mnt/algo_train/anurbha/conda_envs/pytorch_1_8/compiler_compat -L/mnt/algo_train/anurbha/conda_envs/pytorch_1_8/lib -Wl,-rpath=/mnt/algo_train/anurbha/conda_envs/pytorch_1_8/lib -Wl,--no-as-needed -Wl,--sysroot=/ /tmp/pip-req-build-_33twrrb/build/temp.linux-x86_64-cpython-37/tmp/pip-req-build-_33twrrb/src/bindings.o /tmp/pip-req-build-_33twrrb/build/temp.linux-x86_64-cpython-37/tmp/pip-req-build-_33twrrb/src/gridencoder.o -L/mnt/sqnap_colomirror/abrawat/envs/torch3d/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-cpython-37/_gridencoder.cpython-37m-x86_64-linux-gnu.so
    g++: error: /tmp/pip-req-build-_33twrrb/build/temp.linux-x86_64-cpython-37/tmp/pip-req-build-_33twrrb/src/bindings.o: No such file or directory
    g++: error: /tmp/pip-req-build-_33twrrb/build/temp.linux-x86_64-cpython-37/tmp/pip-req-build-_33twrrb/src/gridencoder.o: No such file or directory
    error: command '/usr/bin/g++' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /mnt/sqnap_colomirror/abrawat/envs/torch3d/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-_33twrrb/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-_33twrrb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6y9cc4v7/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/sqnap_colomirror/abrawat/envs/torch3d/include/python3.7m/gridencoder Check the logs for full command output.

```

There is similar issues with the `raymarching` package.
Could you point me to what I might be doing wrong!

TIA!

**Comment by ashawkey** [comment]
@abhayraw1 Hi, could you post more details, such as the OS, CUDA version, and PyTorch version?

**Comment by abhayraw1** [comment]
Here are the details:

```
(torch3d) abrawat@sgscccdl0002 [11:49:15] [/pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/raymarching] [main *]
-> % python -c "import torch; print(torch.__version__)"
1.8.1
(torch3d) abrawat@sgscccdl0002 [11:49:22] [/pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/raymarching] [main *]
-> % nvcc -V                                           
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
(torch3d) abrawat@sgscccdl0002 [11:49:25] [/pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/raymarching] [main *]
-> % lsb_release -a                                    
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
(torch3d) abrawat@sgscccdl0002 [11:49:28] [/pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/raymarching] [main *]
```


I see that the builds were tested on CUDA version >= `10.2`, so I'm currently working on building with CUDA `10.2`, `gcc 7.4`  (Ubuntu 18.04.4 LTS). I also noticed that I get similar error messages in this setting (stack trace below).
```
(torch3d) abrawat@sgscccdl0002 [11:42:14] [/pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/raymarching] [main *]
-> % python setup.py build_ext --inplace
running build_ext
building '_raymarching' extension
Emitting ninja build file /pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/raymarching/build/temp.linux-x86_64-cpython-37/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2
g++ -pthread -B /mnt/algo_train/anurbha/conda_envs/pytorch_1_8/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /mnt/algo_train/anurbha/conda_envs/pytorch_1_8/compiler_compat -L/mnt/algo_train/anurbha/conda_envs/pytorch_1_8/lib -Wl,-rpath=/mnt/algo_train/anurbha/conda_envs/pytorch_1_8/lib -Wl,--no-as-needed -Wl,--sysroot=/ /pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/raymarching/build/temp.linux-x86_64-cpython-37/pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/raymarching/src/bindings.o /pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/raymarching/build/temp.linux-x86_64-cpython-37/pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/raymarching/src/raymarching.o -L/mnt/sqnap_colomirror/abrawat/envs/torch3d/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-cpython-37/_raymarching.cpython-37m-x86_64-linux-gnu.so
g++: error: /pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/raymarching/build/temp.linux-x86_64-cpython-37/pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/raymarching/src/bindings.o: No such file or directory
g++: error: /pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/raymarching/build/temp.linux-x86_64-cpython-37/pfs/rdi/cei/algo_train/abrawat/projects/torch-ngp/raymarching/src/raymarching.o: No such file or directory
error: command '/usr/bin/g++' failed with exit code 1
```

**Comment by ashawkey** [comment]
This is strange, I haven't met this problem. Could you try to install some other packages that require building extensions? For example, `pip install torch-scatter` following [this](https://github.com/rusty1s/pytorch_scatter#from-source)?

**Comment by abhayraw1** [comment]
Got it working!
So apparently I did not have the python development libraries installed! This caused the `ninja` build to fail and therefore the object files weren't generated. Came to know about this when I tried to manually run ninja to compile.

**Comment by Tejas-Deo** [comment]
> Got it working! So apparently I did not have the python development libraries installed! This caused the `ninja` build to fail and therefore the object files weren't generated. Came to know about this when I tried to manually run ninja to compile.

What did you do to solve this problem? Can you please tell me?

**Comment by ChengsongLu** [comment]
> Got it working! So apparently I did not have the python development libraries installed! This caused the `ninja` build to fail and therefore the object files weren't generated. Came to know about this when I tried to manually run ninja to compile.

How did you solve this?
