### ISSUE TITLE
fail to import shencoder after run torch-ngp several times

### ISSUE THREAD

**Issue by ShadowBbBb** [ashawkey/torch-ngp#147]
I already successfully run torch-ngp several times, and a new problem occured this time.
Here is the detail bug report:

Traceback (most recent call last):
  File "D:\research\torch-ngp\shencoder\sphere_harmonics.py", line 10, in <module>
    import _shencoder as _backend
ModuleNotFoundError: No module named '_shencoder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_nerf.py", line 93, in <module>
    model = NeRFNetwork(
  File "D:\research\torch-ngp\nerf\network.py", line 52, in __init__
    self.encoder_dir, self.in_dim_dir = get_encoder(encoding_dir)
  File "D:\research\torch-ngp\encoding.py", line 60, in get_encoder
    from shencoder import SHEncoder
  File "D:\research\torch-ngp\shencoder\__init__.py", line 1, in <module>
    from .sphere_harmonics import SHEncoder
  File "D:\research\torch-ngp\shencoder\sphere_harmonics.py", line 12, in <module>
    from .backend import _backend
  File "D:\research\torch-ngp\shencoder\backend.py", line 32, in <module>
    _backend = load(name='_sh_encoder',
  File "D:\Anaconda\envs\torch-ngp\lib\site-packages\torch\utils\cpp_extension.py", line 1144, in load
    return _jit_compile(
  File "D:\Anaconda\envs\torch-ngp\lib\site-packages\torch\utils\cpp_extension.py", line 1371, in _jit_compile
    baton.wait()
  File "D:\Anaconda\envs\torch-ngp\lib\site-packages\torch\utils\file_baton.py", line 42, in wait
    time.sleep(self.wait_seconds)
KeyboardInterrupt

**Comment by ShadowBbBb** [comment]
Repo: stupid question, as i run torch-ngp in wrong environment
