### ISSUE TITLE
_raymarching_face/_raymarching_face.so: cannot open shared object file

### ISSUE THREAD

**Issue by waityousea** [ashawkey/torch-ngp#148]
Traceback (most recent call last):
  File "/data/scidata/Artra_Soong/RAD-NeRF/raymarching/raymarching.py", line 10, in <module>
    import _raymarching_face as _backend
ModuleNotFoundError: No module named '_raymarching_face'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/scidata/Artra_Soong/RAD-NeRF/test.py", line 131, in <module>
    from nerf.network import NeRFNetwork
  File "/data/scidata/Artra_Soong/RAD-NeRF/nerf/network.py", line 7, in <module>
    from .renderer import NeRFRenderer
  File "/data/scidata/Artra_Soong/RAD-NeRF/nerf/renderer.py", line 10, in <module>
    import raymarching
  File "/data/scidata/Artra_Soong/RAD-NeRF/raymarching/__init__.py", line 1, in <module>
    from .raymarching import *
  File "/data/scidata/Artra_Soong/RAD-NeRF/raymarching/raymarching.py", line 12, in <module>
    from .backend import _backend
  File "/data/scidata/Artra_Soong/RAD-NeRF/raymarching/backend.py", line 31, in <module>
    _backend = load(name='_raymarching_face',
  File "/home/amax/.conda/envs/RAD-NeRF/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/amax/.conda/envs/RAD-NeRF/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1534, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/amax/.conda/envs/RAD-NeRF/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1936, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: /home/amax/.cache/torch_extensions/py39_cu116/_raymarching_face/_raymarching_face.so: cannot open shared object file: No such file or directory

**Comment by Then0109** [comment]
i also met this problem...

**Comment by icommonweal2023** [comment]
如何解决？

**Comment by yasaman95** [comment]
I am also facing this problem. Did anyone fix it?
