### ISSUE TITLE
ModuleNotFoundError: No module named '_raymarching'

### ISSUE THREAD

**Issue by Soumya-Sharma-20** [ashawkey/torch-ngp#184]
**While running 
!python main_nerf.py data/specs1light2 --workspace data/specs1light2 --iters 15000 --num_steps 128 --upsample_steps 128 --fp16 --bound 1.0 --scale 0.8 --dt_gamma 0 --tcnn
This issue occured.**

```
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab Notebooks/nerf2/torch-ngp/raymarching/raymarching.py", line 10, in <module>
    import _raymarching as _backend
ModuleNotFoundError: No module named '_raymarching'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab Notebooks/nerf2/torch-ngp/main_nerf2.py", line 85, in <module>
    from nerf.network_tcnn import NeRFNetwork
  File "/content/drive/MyDrive/Colab Notebooks/nerf2/torch-ngp/nerf/network_tcnn.py", line 9, in <module>
    from .renderer import NeRFRenderer
  File "/content/drive/MyDrive/Colab Notebooks/nerf2/torch-ngp/nerf/renderer.py", line 9, in <module>
    import raymarching
  File "/content/drive/MyDrive/Colab Notebooks/nerf2/torch-ngp/raymarching/__init__.py", line 1, in <module>
    from .raymarching import *
  File "/content/drive/MyDrive/Colab Notebooks/nerf2/torch-ngp/raymarching/raymarching.py", line 12, in <module>
    from .backend import _backend
  File "/content/drive/MyDrive/Colab Notebooks/nerf2/torch-ngp/raymarching/backend.py", line 31, in <module>
    _backend = load(name='_raymarching',
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension '_raymarching': [1/3] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=_raymarching -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/lib/python3.10/dist-packages/torch/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.10/dist-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -c '/content/drive/MyDrive/Colab Notebooks/nerf2/torch-ngp/raymarching/src/raymarching.cu' -o raymarching.cuda.o 
FAILED: raymarching.cuda.o 
/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=_raymarching -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/lib/python3.10/dist-packages/torch/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.10/dist-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -c '/content/drive/MyDrive/Colab Notebooks/nerf2/torch-ngp/raymarching/src/raymarching.cu' -o raymarching.cuda.o 
In file included from /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/string_view.h:4,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/StringUtil.h:6,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/Exception.h:5,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/Generator.h:11,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/ATen/Context.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/ATen/cuda/CUDAContext.h:18,
                 from /content/drive/MyDrive/Colab Notebooks/nerf2/torch-ngp/raymarching/src/raymarching.cu:5:
/usr/local/lib/python3.10/dist-packages/torch/include/c10/util/C++17.h:27:2: error: #error You need C++17 to compile PyTorch
   27 | #error You need C++17 to compile PyTorch
      |  ^~~~~
In file included from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /content/drive/MyDrive/Colab Notebooks/nerf2/torch-ngp/raymarching/src/raymarching.cu:6:
/usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:4:2: error: #error C++17 or later compatible compiler is required to use PyTorch.
    4 | #error C++17 or later compatible compiler is required to use PyTorch.
      |  ^~~~~
In file included from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:4,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:9,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /content/drive/MyDrive/Colab Notebooks/nerf2/torch-ngp/raymarching/src/raymarching.cu:6:
/usr/local/lib/python3.10/dist-packages/torch/include/ATen/ATen.h:4:2: error: #error C++17 or later compatible compiler is required to use ATen.
    4 | #error C++17 or later compatible compiler is required to use ATen.
      |  ^~~~~
[2/3] c++ -MMD -MF bindings.o.d -DTORCH_EXTENSION_NAME=_raymarching -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/lib/python3.10/dist-packages/torch/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.10/dist-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -std=c++14 -c '/content/drive/MyDrive/Colab Notebooks/nerf2/torch-ngp/raymarching/src/bindings.cpp' -o bindings.o 
FAILED: bindings.o 
c++ -MMD -MF bindings.o.d -DTORCH_EXTENSION_NAME=_raymarching -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/lib/python3.10/dist-packages/torch/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.10/dist-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -std=c++14 -c '/content/drive/MyDrive/Colab Notebooks/nerf2/torch-ngp/raymarching/src/bindings.cpp' -o bindings.o 
In file included from /usr/local/lib/python3.10/dist-packages/torch/include/torch/extension.h:5,
                 from /content/drive/MyDrive/Colab Notebooks/nerf2/torch-ngp/raymarching/src/bindings.cpp:1:
/usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:4:2: error: #error C++17 or later compatible compiler is required to use PyTorch.
    4 | #error C++17 or later compatible compiler is required to use PyTorch.
      |  ^~~~~
In file included from /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/string_view.h:4,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/StringUtil.h:6,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/Exception.h:5,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/c10/core/Device.h:5,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/TensorBody.h:11,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/Tensor.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/ATen/Tensor.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/extension.h:5,
                 from /content/drive/MyDrive/Colab Notebooks/nerf2/torch-ngp/raymarching/src/bindings.cpp:1:
/usr/local/lib/python3.10/dist-packages/torch/include/c10/util/C++17.h:27:2: error: #error You need C++17 to compile PyTorch
   27 | #error You need C++17 to compile PyTorch
      |  ^~~~~
In file included from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:4,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:9,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/extension.h:5,
                 from /content/drive/MyDrive/Colab Notebooks/nerf2/torch-ngp/raymarching/src/bindings.cpp:1:
/usr/local/lib/python3.10/dist-packages/torch/include/ATen/ATen.h:4:2: error: #error C++17 or later compatible compiler is required to use ATen.
    4 | #error C++17 or later compatible compiler is required to use ATen.
      |  ^~~~~
In file included from /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/ivalue.h:1499,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/List_inl.h:4,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/List.h:490,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/IListRef_inl.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/IListRef.h:632,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/ATen/WrapDimUtils.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/ATen/TensorNames.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/ATen/NamedTensorUtils.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/autograd/variable.h:11,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/extension.h:5,
                 from /content/drive/MyDrive/Colab Notebooks/nerf2/torch-ngp/raymarching/src/bindings.cpp:1:
/usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/ivalue_inl.h: In lambda function:
/usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/ivalue_inl.h:1061:30: error: ‘is_convertible_v’ is not a member of ‘std’; did you mean ‘is_convertible’?
 1061 |         if constexpr (::std::is_convertible_v<typename c10::invoke_result_t<T &&, Future&>, IValueWithStorages>) {
      |                              ^~~~~~~~~~~~~~~~
      |                              is_convertible
/usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/ivalue_inl.h:1061:91: error: expected ‘(’ before ‘,’ token
 1061 |         if constexpr (::std::is_convertible_v<typename c10::invoke_result_t<T &&, Future&>, IValueWithStorages>) {
      |                                                                                           ^
/usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/ivalue_inl.h:1061:111: error: expected primary-expression before ‘>’ token
 1061 |         if constexpr (::std::is_convertible_v<typename c10::invoke_result_t<T &&, Future&>, IValueWithStorages>) {
      |                                                                                                               ^
/usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/ivalue_inl.h:1061:112: error: expected primary-expression before ‘)’ token
 1061 |         if constexpr (::std::is_convertible_v<typename c10::invoke_result_t<T &&, Future&>, IValueWithStorages>) {
      |                                                                                                                ^
In file included from /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/boxing/KernelFunction_impl.h:1,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/boxing/KernelFunction.h:251,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/op_registration/op_registration.h:11,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/library.h:68,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/autograd/autograd_not_implemented_fallback.h:3,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/autograd.h:4,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /usr/local/lib/python3.10/dist-packages/torch/include/torch/extension.h:5,
                 from /content/drive/MyDrive/Colab Notebooks/nerf2/torch-ngp/raymarching/src/bindings.cpp:1:
/usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/boxing/impl/boxing.h: In static member function ‘static Result c10::impl::BoxedKernelWrapper<Result(Args ...), typename std::enable_if<((c10::guts::conjunction<c10::guts::disjunction<std::is_constructible<c10::IValue, typename std::decay<Args>::type>, std::is_same<c10::TensorOptions, typename std::decay<Args>::type> >...>::value && c10::guts::conjunction<c10::guts::disjunction<c10::impl::has_ivalue_to<T, void>, std::is_same<void, ReturnType> >, c10::guts::negation<std::is_lvalue_reference<_Tp> > >::value) && (! c10::impl::is_tuple_of_mutable_tensor_refs<Result>::value)), void>::type>::call(const c10::BoxedKernel&, const c10::OperatorHandle&, c10::DispatchKeySet, Args ...)’:
/usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/boxing/impl/boxing.h:229:25: error: ‘is_same_v’ is not a member of ‘std’; did you mean ‘is_same’?
  229 |     if constexpr (!std::is_same_v<void, Result>) {
      |                         ^~~~~~~~~
      |                         is_same
/usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/boxing/impl/boxing.h:229:35: error: expected primary-expression before ‘void’
  229 |     if constexpr (!std::is_same_v<void, Result>) {
      |                                   ^~~~
/usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/boxing/impl/boxing.h:229:35: error: expected ‘)’ before ‘void’
/usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/boxing/impl/boxing.h:229:18: note: to match this ‘(’
  229 |     if constexpr (!std::is_same_v<void, Result>) {
      |                  ^
ninja: build stopped: subcommand failed.
```

**Even after verifying the gcc version , cudnn version , gpu version ,python and pyTorch compatibilities , the issue is not getting resolved .
import torch
print(torch.__version__)
!g++ --version

2.1.0+cu118
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

import torch
print(torch.backends.cudnn.version())
8700**

Can anyone help with the debugging of this issue?

**Comment by elliot19soltani** [comment]
I have the exact same issue too.
I run the code on colab and it returns this error.

**Comment by Soumya-Sharma-20** [comment]
> I have the exact same issue too. I run the code on colab and it returns this error.

You need to rebuild raymarching from scratch and then run the env again after installing packages, it will work , there might be some new version issues / compatibility issues because of which this issue occured

**Comment by KangShengYu** [comment]
Same issue too, I noticed that "error: #error C++17 or later compatible compiler is required to use PyTorch.", and I am trying to resolve it

**Comment by KangShengYu** [comment]
Change raymarching/backend.py, Line 7 & 13 and raymarching/setup.py, Line 8 & 14, "c++14" -> "c++17", and recompile it by ` python setup.py build_ext --inplace && pip install .`

Same operation for gridencode, shencoder, and freqencoder

**Comment by TigerHix** [comment]
> Change raymarching/backend.py, Line 7 & 13 and raymarching/setup.py, Line 8 & 14, "c++14" -> "c++17", and recompile it by ` python setup.py build_ext --inplace && pip install .`
> 
> Same operation for gridencode, shencoder, and freqencoder

This worked for me. Thank you very much!

**Comment by Joy2Boy** [comment]
> Change raymarching/backend.py, Line 7 & 13 and raymarching/setup.py, Line 8 & 14, "c++14" -> "c++17", and recompile it by ` python setup.py build_ext --inplace && pip install .`
> 
> Same operation for gridencode, shencoder, and freqencoder

why i run python setup.py `build_ext --inplace && pip install` .occurs the problem below?How can i solve it ?
running build_ext
```
Traceback (most recent call last):
  File "setup.py", line 44, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/Newdisk2/benke/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 396, in build_extensions
    self._check_abi()
  File "/home/Newdisk2/benke/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 767, in _check_abi
    check_compiler_abi_compatibility(compiler)
  File "/home/Newdisk2/benke/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 300, in check_compiler_abi_compatibility
    if not check_compiler_ok_for_platform(compiler):
  File "/home/Newdisk2/benke/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 257, in check_compiler_ok_for_platform
    which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['which', 'x86_64-linux-gnu-g++']' returned non-zero exit status 1.
```

**Comment by Les1a** [comment]
> Change raymarching/backend.py, Line 7 & 13 and raymarching/setup.py, Line 8 & 14, "c++14" -> "c++17", and recompile it by ` python setup.py build_ext --inplace && pip install .`
> 
> Same operation for gridencode, shencoder, and freqencoder

it works! thanks a lot

**Comment by DarcyFan** [comment]
> Change raymarching/backend.py, Line 7 & 13 and raymarching/setup.py, Line 8 & 14, "c++14" -> "c++17", and recompile it by ` python setup.py build_ext --inplace && pip install .`
> 
> Same operation for gridencode, shencoder, and freqencoder

I searched a lot of web pages to solve this problem, thank you very much for the solution, it works for me!
