### ISSUE TITLE
problem when run the code

### ISSUE THREAD

**Issue by Holmes-Alan** [ashawkey/torch-ngp#29]
When I run

python main_nerf.py data/fox --workspace trial_nerf --fp16 --ff --cuda_ray --gui

I got the following error,

Traceback (most recent call last):
  File "C:\Users\zhisong_liu\Miniconda3\envs\ngp\lib\site-packages\torch\utils\cpp_extension.py", line 1740, in _run_ninja_build
    subprocess.run(
  File "C:\Users\zhisong_liu\Miniconda3\envs\ngp\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

I tried to fix the problem on the  '['ninja', '-v']' by '['ninja', '--version']', but I got another problem as,

Traceback (most recent call last):
  File "main_nerf.py", line 53, in <module>
    from nerf.network import NeRFNetwork
  File "D:\torch-ngp\nerf\network.py", line 5, in <module>
    from encoding import get_encoder
  File "D:\torch-ngp\encoding.py", line 5, in <module>
    from hashencoder import HashEncoder
  File "D:\torch-ngp\hashencoder\__init__.py", line 1, in <module>
    from .hashgrid import HashEncoder
  File "D:\torch-ngp\hashencoder\hashgrid.py", line 9, in <module>
    from .backend import _backend
  File "D:\torch-ngp\hashencoder\backend.py", line 6, in <module>
    _backend = load(name='_hash_encoder',
  File "C:\Users\Miniconda3\envs\ngp\lib\site-packages\torch\utils\cpp_extension.py", line 1144, in load
    return _jit_compile(
  File "C:\Users\Miniconda3\envs\ngp\lib\site-packages\torch\utils\cpp_extension.py", line 1382, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "C:\Users\Miniconda3\envs\ngp\lib\site-packages\torch\utils\cpp_extension.py", line 1775, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: DLL load failed while importing _hash_encoder: The specified module could not be found.

What should I do?

_Originally posted by @Holmes-Alan in https://github.com/ashawkey/torch-ngp/issues/26#issuecomment-1070382975_

**Comment by ashawkey** [comment]
Honestly I'm haven't tested it on window, so I'm not familiar with the error.
Could you verify the environment, e.g., torch and ninja version? Could you build other pytorch CUDA extensions, like the `tiny-cuda-nn` by `pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch`?
(Still, I would recommend trying to run the program in Linux systems, such as the WSL)

**Comment by Holmes-Alan** [comment]
OK. Thank you for your response!

**Comment by ziyueju123** [comment]
> 好的。谢谢你的回复！

Have you solved this problem, and how to solve it? Looking forward to your reply!

**Comment by Zdream02** [comment]
> > 好的。谢谢你的回复！
>
> Have you solved this problem, and how to solve it? Looking forward to your reply!
Have you solved this problem, and how to solve it? Looking forward to your reply!
