### ISSUE TITLE
Distributed data parallel training

### ISSUE THREAD

**Issue by xmk2222** [ashawkey/torch-ngp#30]
I'm trying to train torch-ngp on multiple GPUs.

I modified the dataloader by passing a `distributedSampler`, and passed the `local_rank` and `world_size` to `Trainer`,  then run the script by `torch.distributed.run`.

The training process was normal before several epochs(e.g. 6), then crashed reporting this:

```
Traceback (most recent call last):                                                                                                                                     
  File "train_nerf_ddp.py", line 207, in <module>                                                                                                                      
    trainer.train(train_loader, valid_loader, opt.num_epochs)                                                                                                          
  File "/data/torch-ngp/nerf_ddp/utils.py", line 407, in train                                                                                                         
    self.train_one_epoch(train_loader)                                                                                                                                 
  File "/data/torch-ngp/nerf_ddp/utils.py", line 621, in train_one_epoch                                                                                               
    preds, truths, loss = self.train_step(data)                                                                                                                        
  File "/data/torch-ngp/nerf_ddp/utils.py", line 303, in train_step                                                                                                    
    outputs = self.model.render(rays_o, rays_d, z_far=self.depth_scale, staged=False, bg_color=bg_color, perturb=True, **self.conf)                                    
  File "/data/torch-ngp/nerf_ddp/renderer.py", line 404, in render                                                                                                     
    depth, image, depth_var = _run(rays_o, rays_d, num_steps, upsample_steps, bg_color, perturb, z_far=z_far)                                                          
  File "/data/torch-ngp/nerf_ddp/renderer.py", line 164, in run                                                                                                        
    sigmas, rgbs = self(pts.reshape(B, -1, 3), dirs.reshape(B, -1, 3))                                                                                                 
  File "/data/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl                                                    
    return forward_call(*input, **kwargs)                                                                                                                              
  File "/data/torch-ngp/nerf_ddp/network.py", line 73, in forward                                                                                                      
    x = self.encoder(x, bound=self.bound)                                                                                                                              
  File "/data/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl                                                    
    return forward_call(*input, **kwargs)                                                                                                                              
  File "/data/torch-ngp/hashencoder/hashgrid.py", line 137, in forward                                                                                                 
    outputs = hash_encode(inputs, self.embeddings, self.offsets, self.per_level_scale, self.base_resolution, inputs.requires_grad)                                     
  File "/data/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 94, in decorate_fwd                                               
    return fwd(*args, **kwargs)                                                                                                                                        
  File "/data/torch-ngp/hashencoder/hashgrid.py", line 41, in forward                                                                                                  
    outputs = outputs.permute(1, 0, 2).reshape(B, L * C)      
RuntimeError: CUDA error: an illegal memory access was encountered
loss=0.0212 (0.0189), psnr=14.04 (15.27):    4% 1/23 [00:00<00:19,  1.12it/s]terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at /opt/conda/conda-bld/pytorch_1640811806235/work/c10/cuda/CUDACachingAllocator.cpp:1211 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f20ca556d62 in /data/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1c613 (0x7f210fa74613 in /data/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x1a2 (0x7f210fa75022 in /data/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0xa4 (0x7f20ca540314 in /data/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x299129 (0x7f2163a7c129 in /data/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0xada181 (0x7f21642bd181 in /data/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #6: THPVariable_subclass_dealloc(_object*) + 0x292 (0x7f21642bd482 in /data/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x10d0fc (0x55a5309840fc in /data/miniconda3/envs/ngp/bin/python)
frame #8: <unknown function> + 0x10fbcc (0x55a530986bcc in /data/miniconda3/envs/ngp/bin/python)
frame #9: <unknown function> + 0x217ca3 (0x55a530a8eca3 in /data/miniconda3/envs/ngp/bin/python)
frame #10: <unknown function> + 0x10fd05 (0x55a530986d05 in /data/miniconda3/envs/ngp/bin/python)
frame #11: <unknown function> + 0x1aa047 (0x55a530a21047 in /data/miniconda3/envs/ngp/bin/python)
frame #12: <unknown function> + 0x10d0fc (0x55a5309840fc in /data/miniconda3/envs/ngp/bin/python)
frame #13: <unknown function> + 0x10fbcc (0x55a530986bcc in /data/miniconda3/envs/ngp/bin/python)
frame #14: <unknown function> + 0x217ca3 (0x55a530a8eca3 in /data/miniconda3/envs/ngp/bin/python)
frame #15: <unknown function> + 0x10fd35 (0x55a530986d35 in /data/miniconda3/envs/ngp/bin/python)
frame #16: <unknown function> + 0x1aa047 (0x55a530a21047 in /data/miniconda3/envs/ngp/bin/python)
frame #17: <unknown function> + 0x10fd35 (0x55a530986d35 in /data/miniconda3/envs/ngp/bin/python)
frame #18: <unknown function> + 0x1aa047 (0x55a530a21047 in /data/miniconda3/envs/ngp/bin/python)
frame #19: _PyModule_ClearDict + 0x473 (0x55a530a1d723 in /data/miniconda3/envs/ngp/bin/python)
frame #20: PyImport_Cleanup + 0x408 (0x55a530a62f88 in /data/miniconda3/envs/ngp/bin/python)
frame #21: Py_FinalizeEx + 0x79 (0x55a530ac94f9 in /data/miniconda3/envs/ngp/bin/python)
frame #22: Py_RunMain + 0x1bc (0x55a530acc87c in /data/miniconda3/envs/ngp/bin/python)
frame #23: Py_BytesMain + 0x39 (0x55a530accc69 in /data/miniconda3/envs/ngp/bin/python)
frame #24: __libc_start_main + 0xe7 (0x7f219c264c87 in /lib/x86_64-linux-gnu/libc.so.6)
frame #25: <unknown function> + 0x1f7427 (0x55a530a6e427 in /data/miniconda3/envs/ngp/bin/python)
```

I tried to use `--tcnn`, it crashed, too:
```
Traceback (most recent call last):                                                                                                                                     
  File "train_nerf_ddp.py", line 207, in <module>                                                                                                                      
    trainer.train(train_loader, valid_loader, opt.num_epochs)                                                                                                          
  File "/data/torch-ngp/nerf_ddp/utils.py", line 407, in train                                                                                                         
    self.train_one_epoch(train_loader)
  File "/data/torch-ngp/nerf_ddp/utils.py", line 621, in train_one_epoch
    preds, truths, loss = self.train_step(data)
  File "/data/torch-ngp/nerf_ddp/utils.py", line 303, in train_step
    outputs = self.model.render(rays_o, rays_d, z_far=self.depth_scale, staged=False, bg_color=bg_color, perturb=True, **self.conf)
  File "/data/torch-ngp/nerf_ddp/renderer.py", line 404, in render
    depth, image, depth_var = _run(rays_o, rays_d, num_steps, upsample_steps, bg_color, perturb, z_far=z_far)
  File "/data/torch-ngp/nerf_ddp/renderer.py", line 164, in run
    sigmas, rgbs = self(pts.reshape(B, -1, 3), dirs.reshape(B, -1, 3))
  File "/data/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/torch-ngp/nerf_ddp/network_tcnn.py", line 93, in forward
    x = self.encoder(x)
  File "/data/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/miniconda3/envs/ngp/lib/python3.8/site-packages/tinycudann/modules.py", line 82, in forward
    output = _module_function.apply(                                                                                                                                   
  File "/data/miniconda3/envs/ngp/lib/python3.8/site-packages/tinycudann/modules.py", line 31, in forward                                                              
    native_ctx, output = native_tcnn_module.fwd(input, params)   
   RuntimeError: /tmp/pip-req-build-3voywypo/include/tiny-cuda-nn/gpu_memory.h:574 cudaDeviceSynchronize() failed with error an illegal memory access was encount[100/234]
loss=0.0471 (0.0579), psnr=8.83 (7.39):    4% 1/23 [00:01<00:23,  1.05s/it]Could not free memory: /tmp/pip-req-build-3voywypo/include/tiny-cuda-nn/gpu_memory.h:128 cud
aFree(rawptr) failed with error an illegal memory access was encountered                                                                                               
Could not free memory: /tmp/pip-req-build-3voywypo/include/tiny-cuda-nn/gpu_memory.h:128 cudaFree(rawptr) failed with error an illegal memory access was encountered   
/tmp/pip-req-build-3voywypo/src/fully_fused_mlp.cu:706 cudaEventDestroy(m_training_splitk_events[i]) failed with error an illegal memory access was encountered        
/tmp/pip-req-build-3voywypo/src/fully_fused_mlp.cu:707 cudaStreamDestroy(m_training_splitk_streams[i]) failed with error an illegal memory access was encountered      
/tmp/pip-req-build-3voywypo/src/fully_fused_mlp.cu:706 cudaEventDestroy(m_training_splitk_events[i]) failed with error an illegal memory access was encountered        
/tmp/pip-req-build-3voywypo/src/fully_fused_mlp.cu:707 cudaStreamDestroy(m_training_splitk_streams[i]) failed with error an illegal memory access was encountered      
/tmp/pip-req-build-3voywypo/src/fully_fused_mlp.cu:706 cudaEventDestroy(m_training_splitk_events[i]) failed with error an illegal memory access was encountered        
/tmp/pip-req-build-3voywypo/src/fully_fused_mlp.cu:707 cudaStreamDestroy(m_training_splitk_streams[i]) failed with error an illegal memory access was encountered      
/tmp/pip-req-build-3voywypo/src/fully_fused_mlp.cu:706 cudaEventDestroy(m_training_splitk_events[i]) failed with error an illegal memory access was encountered        
/tmp/pip-req-build-3voywypo/src/fully_fused_mlp.cu:707 cudaStreamDestroy(m_training_splitk_streams[i]) failed with error an illegal memory access was encountered
/tmp/pip-req-build-3voywypo/src/fully_fused_mlp.cu:706 cudaEventDestroy(m_training_splitk_events[i]) failed with error an illegal memory access was encountered
/tmp/pip-req-build-3voywypo/src/fully_fused_mlp.cu:707 cudaStreamDestroy(m_training_splitk_streams[i]) failed with error an illegal memory access was encountered
loss=0.0592 (0.0557), psnr=7.68 (7.02):   17% 4/23 [00:01<00:05,  3.23it/s]terminate called after throwing an instance of 'c10::Error'
  what():  NCCL error in: /opt/conda/conda-bld/pytorch_1640811806235/work/torch/csrc/distributed/c10d/NCCLUtils.hpp:181, unhandled cuda error, NCCL version 21.0.3
Process Group destroyed on rank 2
Exception raised from ncclCommAbort at /opt/conda/conda-bld/pytorch_1640811806235/work/torch/csrc/distributed/c10d/NCCLUtils.hpp:181 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f2124ff7d62 in /data/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7f2124ff468b in /data/miniconda3/envs/ngp/lib/python3.8/sit
e-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x107c48e (0x7f2176de148e in /data/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #3: c10d::ProcessGroupNCCL::~ProcessGroupNCCL() + 0x113 (0x7f2176dc9d93 in /data/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #4: c10d::ProcessGroupNCCL::~ProcessGroupNCCL() + 0x9 (0x7f2176dc9fb9 in /data/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #5: <unknown function> + 0xe67b76 (0x7f21bf0ebb76 in /data/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0xe4d885 (0x7f21bf0d1885 in /data/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x2a1b00 (0x7f21be525b00 in /data/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x2a2d6e (0x7f21be526d6e in /data/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0x10d098 (0x56344cddb098 in /data/miniconda3/envs/ngp/bin/python)
frame #10: <unknown function> + 0x10fbcc (0x56344cdddbcc in /data/miniconda3/envs/ngp/bin/python)
frame #11: PyDict_Clear + 0x14b (0x56344cddef6b in /data/miniconda3/envs/ngp/bin/python)
frame #12: <unknown function> + 0x110ff9 (0x56344cddeff9 in /data/miniconda3/envs/ngp/bin/python)
frame #13: <unknown function> + 0x130246 (0x56344cdfe246 in /data/miniconda3/envs/ngp/bin/python)
frame #14: _PyGC_CollectNoFail + 0x2a (0x56344cf08a2a in /data/miniconda3/envs/ngp/bin/python)
frame #15: PyImport_Cleanup + 0x2ce (0x56344ceb9e4e in /data/miniconda3/envs/ngp/bin/python)
frame #16: Py_FinalizeEx + 0x79 (0x56344cf204f9 in /data/miniconda3/envs/ngp/bin/python)
frame #17: Py_RunMain + 0x1bc (0x56344cf2387c in /data/miniconda3/envs/ngp/bin/python)
frame #18: Py_BytesMain + 0x39 (0x56344cf23c69 in /data/miniconda3/envs/ngp/bin/python)
frame #19: __libc_start_main + 0xe7 (0x7f21f6d05c87 in /lib/x86_64-linux-gnu/libc.so.6)
frame #20: <unknown function> + 0x1f7427 (0x56344cec5427 in /data/miniconda3/envs/ngp/bin/python)

```

Did I do something wrong? Or does the code simply not support multi-GPU training?

**Comment by xmk2222** [comment]
https://github.com/NVlabs/tiny-cuda-nn/issues/63

Sadly, the `--tcnn` does not support multi-GPU training for sure.

**Comment by ashawkey** [comment]
Yes, multi-GPU training for both CMD and GUI mode has not been supported now (the `local_rank` in trainer is not tested in this repo since it was borrowed from old projects).
In most cases the training speed should be fast enough on one GPU, may I know your using case for multi-GPU?

**Comment by slash-under** [comment]
(coming from the linked issue above)

I've been evaluating torch-ngp as a way to scale NeRF models as my dataset (750 4K images) no longer fits in any available GPU's VRAM -- only about 300 frames fit on a 40 GB A100. I saw there appeared to be some changes to only load portions of the training data at the time, could that support such a use-case?

**Comment by ashawkey** [comment]
@slash-under that's strange, dataset size should not affect the runtime GPU memory, since it is only load one image at a time by default. Are you using the latest version, and not using the flat `--preload` for `NeRFDataset`?

**Comment by xmk2222** [comment]
Thanks! Just looking ways to speed up training, the training time of a single GPU is bearable.

Well, I'm still wondering if it is possible to implement everything in python including the hash-encoding? I think that would enable the training process to be distributed on multiple GPUs. Or perhaps the speedup gained by parallel computing would be cancelled out by the slowdown caused by the python implementation...

**Comment by ashawkey** [comment]
@xmk2222 there is a pure-pytorch implementation [here](https://github.com/yashbhalgat/HashNeRF-pytorch).

**Comment by hturki** [comment]
hey @slash-under - apologies for tooting my own horn a bit, but I've run into similar issues where I've wanted to train NeRFs against thousands of high-resolution images. The best I could come up with is writing randomized batches of rgbs and rays across all of my images to disk as a preprocessing step, and then loading those from disk in chunks. You can take a look at https://github.com/cmusatyalab/mega-nerf/blob/main/mega_nerf/datasets/filesystem_dataset.py for inspiration and would be happy to hear of better suggestions.

**Comment by ashawkey** [comment]
closed for now.
