### ISSUE TITLE
Speed of FFMLP

### ISSUE THREAD

**Issue by jianglongye** [ashawkey/torch-ngp#55]
Hi, thanks for your valuable work!

~When I updated my code to the newest version, I found that FFMLP does not work anymore. Specifically, the program stuck when I specify -ff parameters. Here is the error when I use ctrl c to cancel the program:~

```
Traceback (most recent call last):
  File "/data/jianglong/deploy/nerf/torch-ngp/main_nerf.py", line 63, in <module>
    from nerf.network_ff import NeRFNetwork
  File "/data/jianglong/deploy/nerf/torch-ngp/nerf/network_ff.py", line 7, in <module>
    from ffmlp import FFMLP
  File "/data/jianglong/deploy/nerf/torch-ngp/ffmlp/__init__.py", line 1, in <module>
    from .ffmlp import FFMLP
  File "/data/jianglong/deploy/nerf/torch-ngp/ffmlp/ffmlp.py", line 10, in <module>
    from .backend import _backend
  File "/data/jianglong/deploy/nerf/torch-ngp/ffmlp/backend.py", line 33, in <module>
    _backend = load(name='_ffmlp',
  File "/data/jianglong/miniconda3/envs/nerf_torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1124, in load
    return _jit_compile(
  File "/data/jianglong/miniconda3/envs/nerf_torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1337, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/data/jianglong/miniconda3/envs/nerf_torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1449, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/data/jianglong/miniconda3/envs/nerf_torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1717, in _run_ninja_build
    subprocess.run(
  File "/data/jianglong/miniconda3/envs/nerf_torch/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/data/jianglong/miniconda3/envs/nerf_torch/lib/python3.9/subprocess.py", line 1121, in communicate
    stdout = self.stdout.read()
KeyboardInterrupt
```

~The ffmlp works when I use old version code (maybe 20 days ago).~ My platform is 3090, cuda 11.2, torch 1.10.

~Although I can use tiny-cuda-nn instead, I still want to know is there any change of ffmlp which may cause this issue?~

Thanks again!

---

Update:

After trying more times, suddenly the ffmlp works again. But the speed (35 iter/s) is much worse than tiny-cuda-nn (75 iter/s), is this expected?

**Comment by ashawkey** [comment]
It takes a long time (maybe 1-3 minutes) to compile the extension at first time run.
The speed may depend on your GPU and CUDA environment, you can choose the fastest backbone (`--fp16` /  `--ff` / `--tcnn`) according to your experiments.

**Comment by jianglongye** [comment]
Thanks for your quick response. 

It indeed takes a long time (> 10 min) for me to compile. I believe this is platform dependent.

For me, `--fp16`, `--tcnn` and `--cuda-ray` lead to the fastest running speed.

Thanks again. I will close this issue.
