### ISSUE TITLE
need at least one array to stack

### ISSUE THREAD

**Issue by imistyrain** [ashawkey/torch-ngp#80]
when try to train fern with cmd
```
python scripts/llff2nerf.py data/nerf_llff_data/fern
python main_nerf.py data/nerf_llff_data/fern --workspace trial_nerf -O
```
, got this error

```
Traceback (most recent call last):
  File "main_nerf.py", line 126, in <module>
    train_loader = NeRFDataset(opt, device=device, type='train').dataloader()
  File "***/torch-ngp/nerf/provider.py", line 226, in __init__
    self.poses = torch.from_numpy(np.stack(self.poses, axis=0)) # [N, 4, 4]
  File "<__array_function__ internals>", line 6, in stack
  File "***/python3.7/site-packages/numpy/core/shape_base.py", line 422, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
```
in nerf/provider.py line 196, 
```
f_path = os.path.join(self.root_path, f['file_path'])
```
'/images_4/image001.png', which expect to be 'data/nerf_llff_data/fern/images_4/image001.png'
so change it to
```
f_path = self.root_path+f['file_path']
```

**Comment by ashawkey** [comment]
@imistyrain Hi, thanks for reporting the bug! It has been fixed in https://github.com/ashawkey/torch-ngp/commit/dd2add6e05fa06cf7e82116c49d797ebdc4b7de9.

**Comment by ashawkey** [comment]
@imistyrain Hi, thanks for reporting the bug! It has been fixed in https://github.com/ashawkey/torch-ngp/commit/dd2add6e05fa06cf7e82116c49d797ebdc4b7de9.
