### ISSUE TITLE
Problems about D-Nerf test

### ISSUE THREAD

**Issue by dialogueeeeee** [ashawkey/torch-ngp#89]
When I used the test parameter to load the D-Nerf model for prediction, there was a shape mismatch problem. I didn't change any training parameters, and the error is as follows:

``` 
[INFO] Trainer: ngp | 2022-07-27_16-58-37 | cuda | fp16 | trial_dnerf_jumpingjacks_test2
[INFO] #parameters: 12731168
[INFO] Loading latest checkpoint ...
[INFO] Latest checkpoint is trial_dnerf_jumpingjacks_test2/checkpoints/ngp_ep0150.pth
Traceback (most recent call last):
  File "/home/daiyalun/torch-ngp-main/main_dnerf.py", line 97, in <module>
    trainer = Trainer('ngp', opt, model, device=device, workspace=opt.workspace, criterion=criterion, fp16=opt.fp16, metrics=[PSNRMeter()], use_checkpoint=opt.ckpt)
  File "/home/daiyalun/torch-ngp-main/dnerf/utils.py", line 34, in __init__
    super().__init__(name, opt, model, criterion, optimizer, ema_decay, lr_scheduler, metrics, local_rank, world_size, device, mute, fp16, eval_interval, max_keep_ckpt, workspace, best_mode, use_loss_as_metric, report_metric_at_train, use_checkpoint, use_tensorboardX, scheduler_update_every_step)
  File "/home/daiyalun/torch-ngp-main/nerf/utils.py", line 331, in __init__
    self.load_checkpoint()
  File "/home/daiyalun/torch-ngp-main/nerf/utils.py", line 1016, in load_checkpoint
    missing_keys, unexpected_keys = self.model.load_state_dict(checkpoint_dict['model'], strict=False)
  File "/home/daiyalun/anaconda3/envs/torch-ngp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for NeRFNetwork:
        size mismatch for density_grid: copying a param with shape torch.Size([64, 4, 2097152]) from checkpoint, the shape in current model is torch.Size([64, 2, 2097152]).
        size mismatch for density_bitfield: copying a param with shape torch.Size([64, 1048576]) from checkpoint, the shape in current model is torch.Size([64, 524288]).
        size mismatch for encoder.embeddings: copying a param with shape torch.Size([6589272, 2]) from checkpoint, the shape in current model is torch.Size([6328848, 2]).
```

**Comment by dialogueeeeee** [comment]
My test command is as follows.
```
python main_dnerf.py data/jumpingjacks --workspace trial_dnerf_jumpingjacks -O --test
```

**Comment by collinabidi** [comment]
I'm facing the same error with the most recent version of the code. Could this be a conflict with PyTorch version?

**Comment by ashawkey** [comment]
@collinabidi If it is the same error, it maybe caused by different configs. I fixed another bug (patch_size not found) for dnerf in the latest commit, and you can try now.
