### ISSUE TITLE
LINK : fatal error LNK1104: cannot open file 'python39.lib'

### ISSUE THREAD

**Issue by Milo-Goodfellow-Work** [ashawkey/torch-ngp#91]
**Hello, everyone!**
Putting this in as an issue since it's missing from the tutorial. I think it's something on my end concerning PATH and the linker, but I want to double-check and see if anyone knows a fix.

**The problem:**
When I clone the repository, create a virtual environment where I install requirements.txt, and run the following command from root:
```
python main_nerf.py data/fox --workspace trial_nerf -O --test --tcnn
```

I get a linker error, specifically:
```
LINK : fatal error LNK1104: cannot open file 'python39.lib'
```

The full traceback:
```
Traceback (most recent call last):
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\torch-ngp-main\raymarching\raymarching.py", line 10, in <module>
    import _raymarching as _backend
ModuleNotFoundError: No module named '_raymarching'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1808, in _run_ninja_build
    subprocess.run(
  File "C:\Users\milog\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\torch-ngp-main\main_nerf.py", line 78, in <module>
    from nerf.network_tcnn import NeRFNetwork
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\torch-ngp-main\nerf\network_tcnn.py", line 9, in <module>    from .renderer import NeRFRenderer
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\torch-ngp-main\nerf\renderer.py", line 9, in <module>
    import raymarching
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\torch-ngp-main\raymarching\__init__.py", line 1, in <module>
    from .raymarching import *
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\torch-ngp-main\raymarching\raymarching.py", line 12, in <module>
    from .backend import _backend
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\torch-ngp-main\raymarching\backend.py", line 31, in <module>
    _backend = load(name='_raymarching',
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1202, in load
    return _jit_compile(
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1425, in _jit_compile
    _write_ninja_file_and_build_library(
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1537, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1824, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension '_raymarching': [1/1] "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64/link.exe" raymarching.cuda.o bindings.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda_cu.lib -INCLUDE:?_torch_cuda_cu_linker_symbol_op_cuda@native@at@@YA?AVTensor@2@AEBV32@@Z torch_cuda_cpp.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:D:\Documents\Projects\test_open3d\ImageQualityPipeline\venv\lib\site-packages\torch\lib torch_python.lib /LIBPATH:D:\Documents\Projects\test_open3d\ImageQualityPipeline\venv\Scripts\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib/x64" cudart.lib /out:_raymarching.pyd
FAILED: _raymarching.pyd
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64/link.exe" raymarching.cuda.o bindings.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda_cu.lib -INCLUDE:?_torch_cuda_cu_linker_symbol_op_cuda@native@at@@YA?AVTensor@2@AEBV32@@Z torch_cuda_cpp.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:D:\Documents\Projects\test_open3d\ImageQualityPipeline\venv\lib\site-packages\torch\lib torch_python.lib /LIBPATH:D:\Documents\Projects\test_open3d\ImageQualityPipeline\venv\Scripts\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib/x64" cudart.lib /out:_raymarching.pyd
LINK : fatal error LNK1104: cannot open file 'python39.lib'
ninja: build stopped: subcommand failed.
```

I've added the path where I have python39.lib to my system environment variables, but it doesn't change anything. I'm unsure how to properly indicate to the linker where it should look in this project.

**Question:**
If this is caused because the linker hasn't been properly told where to find 'python39.lib', how can I indicate to the linker where 'python39.lib' is stored? If it isn't, how can I go about fixing the error?
Thank you for reading; I enormously appreciate any feedback. Have a great day.

**Comment by ashawkey** [comment]
@Milo-Goodfellow-Work Hi, I haven't met this error so I'm not very sure. Have you tried [this](https://stackoverflow.com/questions/36419747/link-fatal-error-lnk1104-cannot-open-file-python27-lib)?

**Comment by Milo-Goodfellow-Work** [comment]
> @Milo-Goodfellow-Work Hi, I haven't met this error so I'm not very sure. Have you tried [this](https://stackoverflow.com/questions/36419747/link-fatal-error-lnk1104-cannot-open-file-python27-lib)?

Hey, I think this actually did work to solve my error. I had tried something similar which did the same thing, but when it produced an error I just assumed I was approaching the problem incorrectly (very silly, usually a new error is a good sign.).

The new traceback I'm getting is as follows:
```
File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\torch-ngp-main\raymarching\raymarching.py", line 10, in <module>
    import _raymarching as _backend
ModuleNotFoundError: No module named '_raymarching'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1808, in _run_ninja_build
    subprocess.run(
  File "C:\Users\milog\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\torch-ngp-main\main_nerf.py", line 78, in <module>
    from nerf.network_tcnn import NeRFNetwork
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\torch-ngp-main\nerf\network_tcnn.py", line 9, in <module>
    from .renderer import NeRFRenderer
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\torch-ngp-main\nerf\renderer.py", line 9, in <module>
    import raymarching
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\torch-ngp-main\raymarching\__init__.py", line 1, in <module>
    from .raymarching import *
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\torch-ngp-main\raymarching\raymarching.py", line 12, in <module>
    from .backend import _backend
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\torch-ngp-main\raymarching\backend.py", line 31, in <module>
    _backend = load(name='_raymarching',
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1202, in load
    return _jit_compile(
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1425, in _jit_compile
    _write_ninja_file_and_build_library(
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1537, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "D:\Documents\Projects\test_open3d\ImageQualityPipeline\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1824, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension '_raymarching': [1/1] "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64/link.exe" raymarching.cuda.o bindings.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda_cu.lib -INCLUDE:?_torch_cuda_cu_linker_symbol_op_cuda@native@at@@YA?AVTensor@2@AEBV32@@Z torch_cuda_cpp.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:D:\Documents\Projects\test_open3d\ImageQualityPipeline\venv\lib\site-packages\torch\lib torch_python.lib /LIBPATH:D:\Documents\Projects\test_open3d\ImageQualityPipeline\venv\Scripts\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib/x64" cudart.lib /out:_raymarching.pyd
FAILED: _raymarching.pyd
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64/link.exe" raymarching.cuda.o bindings.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda_cu.lib -INCLUDE:?_torch_cuda_cu_linker_symbol_op_cuda@native@at@@YA?AVTensor@2@AEBV32@@Z torch_cuda_cpp.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:D:\Documents\Projects\test_open3d\ImageQualityPipeline\venv\lib\site-packages\torch\lib torch_python.lib /LIBPATH:D:\Documents\Projects\test_open3d\ImageQualityPipeline\venv\Scripts\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib/x64" cudart.lib /out:_raymarching.pyd
   Creating library _raymarching.lib and object _raymarching.exp
bindings.o : error LNK2019: unresolved external symbol "void __cdecl composite_rays(unsigned int,unsigned int,class at::Tensor,class at::Tensor,class at::Tensor,class at::Tensor,class at::Tensor,class at::Tensor,class at::Tensor,class at::Tensor)" (?composite_rays@@YAXIIVTensor@at@@0000000@Z) referenced in function "void __cdecl pybind11_init__raymarching(class pybind11::module_ &)" (?pybind11_init__raymarching@@YAXAEAVmodule_@pybind11@@@Z)
  Hint on symbols that are defined and could potentially match:
    "void __cdecl composite_rays(unsigned int,unsigned int,class at::Tensor,class at::Tensor,class at::Tensor,class at::Tensor,class at::Tensor,class at::Tensor,class at::Tensor,class at::Tensor)" (?composite_rays@@YAXIIVTensor@at@@0V12@11000@Z)
_raymarching.pyd : fatal error LNK1120: 1 unresolved externals
ninja: build stopped: subcommand failed.
```

If you're up for continuing to help, I'd an enormously appreciate it. 
Separately, I can also open a new issue for this error if you have a preference for me so doing. (Ignore the close and open of the issue, that was a typo on my part.)

**Comment by Milo-Goodfellow-Work** [comment]
@ashawkey Forgot to ping, sorry about the unnescessary comment.
